name: Build wireguard-go for Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    branches: 
      - master
  schedule:
    - cron: 0 8 1 * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: 初始化
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update   
        sudo apt-get -y install cmake git
        cd ~ 
        wget https://dl.google.com/go/go1.13.6.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.13.6.linux-amd64.tar.gz
        echo 'export GOROOT=/usr/local/go' >> .bashrc
        echo 'export GOPATH=$HOME/go' >> .bashrc 
        echo 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> .bashrc
        source $HOME/.bashrc
        mkdir go 
        cd go 
        mkdir bin 
        mkdir src 
        mkdir pkg
    - name: 编译wg
      run: |
        cd /tmp/
        git clone https://github.com/WireGuard/wireguard-tools.git
        git clone git://git.netfilter.org/libmnl
        cd /tmp/libmnl/
        ./autogen.sh --disable-shared --host=mipsel-linux-uclibc
        ./configure
        make
        cd /tmp/wireguard-tools/src/
        env CFLAGS=-I/tmp/libmnl/include LDFLAGS=-L/tmp/libmnl/src/.libs make        
        file wg
    - name: 编译wireguard-go      
      run: |
        go get git.zx2c4.com/wireguard-go
        cd $HOME/go/src/git.zx2c4.com/wireguard-go
        env GOOS=linux GOARCH=mipsle go build        
        file wireguard-go
        cd $HOME/go/bin
    - name : 上传wg
      uses: actions/upload-artifact@master
      with:
        name: wg
        path: /tmp/wireguard-tools/src/
    - name : 上传wireguard-go
      uses: actions/upload-artifact@master
      with:
        name: wireguard-go
        path: ./
